[package]
name = "bevy_rhythm_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
iyes_loopless = "0.7"
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3